name: End to End

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 20

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - run: npm run ci
        env:
          CI: true
          REPLICA_PORT: 8000